### ISSUE TITLE
Selected line out of bounds crash

### ISSUE THREAD

**Issue by TheLostCookie** [adlez27/akorin#16]
When the currently opened project's selected line is greater than the number of lines available in a newly opened fire, an OutOfRangeException occurs.

For example, suppose the the project "SavedProject" only has 5 lines in total, and the current project open in the application has the sixth line selected. Opening SavedProject in this state results in this bug.

**Comment by adlez27** [comment]
Akorin is no longer in development. Any interested users should use RecStar instead.

https://github.com/sdercolin/recstar/
