### ISSUE TITLE
Run Akorin as UTAU plugin

### ISSUE THREAD

**Issue by adlez27** [adlez27/akorin#18]
Executing Akorin from within UTAU as a plugin, making use of this class library: https://github.com/delta-kimigatame/utauPlugin

Destination folder: Top level folder of currently selected voicebank. User can still manually select another folder.
Project file: Does not save a project file when run as a plugin  
Reclist: One line per selected note, text/notes depending on use case per note

**Use case 1 - Overwriting existing recordings**  
The selected note's lyric + any prefixes and suffixes from the prefix map, has a corresponding entry in any oto.ini file in the voicebank and its subfolders.  
Reclist line text: Filename. If the original file is in a subfolder, filename including prefixes/suffixes.
Reclist line note: Note lyric including prefixes/suffixes
When saving the recording
- If overwriting the original file directly, save as normal
- If the original file is in a subfolder, remove the selected line's entry from the subfolder's oto.ini and add it to the top folder's oto.ini with the new filename

**Use case 2 - Adding new recordings**
Reclist line text: Note lyric including prefixes/suffixes

**Comment by kel0926** [comment]
is it possible to use Akorin as a plugin for Open-Utau? I recently started doing utau and found that oremo doesn't work on the new mac systems so I came for akorin, and got a bit stuck...

**Comment by adlez27** [comment]
My apologies, I forgot to close the open issues here.

Akorin is no longer in development. Please use RecStar.
https://github.com/sdercolin/recstar/
