### ISSUE TITLE
Akorin not working on Mac ヽ(°〇°)ﾉ

### ISSUE THREAD

**Issue by misschuu** [adlez27/akorin#22]
Ok so, I know this is an issue but I just wanted to see if this is currently being resolved as like the last build was in 2021 (its 2023).So, I just wanted to know as im suffering here 😭

(adlez27 if you see this I would do anything for this to be fixed

**Comment by adlez27** [comment]
Hello, there are a few reasons this project is no longer being worked on.
- I do not have a modern Mac to test it on, and the M1 chip requires significant changes to software.
- My other projects take higher priority.

For any other developers, I would be glad to pass on Akorin and let someone else take responsibility for it.

For Mac users who need to record voicebanks, I suggest using conventional recording software, such as Garageband. For maximum compatibility, ensure that you record at 44.1kHz sample rate with 1 channel (mono), and export as a 16 bit WAV file.
